name: Test

on:
  workflow_call:

jobs:
  Ubuntu-Make:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf: [Debug, Release]
        arch: [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib

      - name: Make
        run: make test CONFIG=${{ matrix.conf }} ARCH=${{ matrix.arch }}

  Ubuntu-CMake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conf: [Debug, Release]
        arch: [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib

      - name: Build
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.conf }} -DARCH=${{ matrix.arch }}

      - name: Run
        run: cmake --build build --target test --config ${{ matrix.conf }}

      - name: Log
        if: always()
        run: cat build/Testing/Temporary/LastTest.log

  Windows-CMake:
    runs-on: windows-latest
    strategy:
      matrix:
        conf: [Debug, Release]
        arch: [x64, x86]
        include:
          - arch: x64
            warch: x64
          - arch: x86
            warch: Win32

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cmake -S . -B build -A ${{ matrix.warch }} -DCMAKE_BUILD_TYPE=${{ matrix.conf }} -DARCH=${{ matrix.arch }}

      - name: Run
        run: cmake --build build --target run_tests --config ${{ matrix.conf }}

      - name: Log
        if: always()
        run: cat build/Testing/Temporary/LastTest.log
