name: Test

on:
  workflow_call:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gen: [M, C]

    steps:
      - uses: actions/checkout@v4

      - name: Download
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo cgware/build latest --pattern "build-linux-x64.zip"
          unzip "build-linux-x64.zip" -d bin

      - name: Prepare
        run: |
          chmod +x ./bin/build-linux-x64/build
          sudo apt-get update
          sudo apt-get install gcc-multilib lcov -y

      - name: Test
        run: ./bin/build-linux-x64/build -g ${{ matrix.gen }} -a "x64 x86" -c "Debug Release" -t "all test" -O 0

      - name: Log
        if: matrix.gen == 'C'
        run: |
          cat build/Testing/Temporary/LastTest.log
          cat build/x64-Debug/Testing/Temporary/LastTest.log
          cat build/x64-Release/Testing/Temporary/LastTest.log
          cat build/x86-Debug/Testing/Temporary/LastTest.log
          cat build/x86-Release/Testing/Temporary/LastTest.log

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo cgware/build latest --pattern "build-windows-x64.zip"
          unzip "build-windows-x64.zip" -d bin

      - name: Prepare
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '17.14'

      - name: Test
        run: ./bin/build-windows-x64/build -a "x64 x86" -c "Debug Release" -t "all test" -O 0

      - name: Log
        if: always()
        run: |
          cat build/Testing/Temporary/LastTest.log
          cat build/x64/Testing/Temporary/LastTest.log
          cat build/x86/Testing/Temporary/LastTest.log
